# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opis.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nopis.proto\x12\x03\x61pi\"\x1f\n\x0b\x41uthRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x1e\n\x0c\x41uthResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x32:\n\x04\x41uth\x12\x32\n\tCheckAuth\x12\x10.api.AuthRequest\x1a\x11.api.AuthResponse\"\x00\x42\x07Z\x05./apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opis_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005./api'
  _AUTHREQUEST._serialized_start=19
  _AUTHREQUEST._serialized_end=50
  _AUTHRESPONSE._serialized_start=52
  _AUTHRESPONSE._serialized_end=82
  _AUTH._serialized_start=84
  _AUTH._serialized_end=142
# @@protoc_insertion_point(module_scope)
